### ISSUE TITLE
전시 정보 디테일 페이지

### ISSUE THREAD

**Issue by lse415** [Artview2024/Artview_FE#105]
## 📝Description
> 전시 정보 디테일 페이지

## ☑️Todo
- [x] 전시 정보 불러오기
- [x] 전시 관련 소통 게시글 불러오기
- [x] 전시 관련 소통 게시글 더보기

## 💬 ETC
- 기타 사항
