### ISSUE TITLE
추천사용자

### ISSUE THREAD

**Issue by lse415** [Artview2024/Artview_FE#110]
## 📝Description
> 소통 페이지 추천사용자 보주기

## ☑️Todo
- [x] RecommendedUsers component 생성
- [x] Community 무한스크롤데이터 첫번째 데이터 다음에 보여주기
- [x] 사용자 누르면 해당 사용자프로필 화면

## 💬 ETC
- 기타 사항
