### ISSUE TITLE
Recording

### ISSUE THREAD

**Issue by lse415** [Artview2024/Artview_FE#5]
## 📝Description
> Recording Start Screen/Recording Screen

## ☑️Todo
- [x] icons
- [x] Datepicker
- [x] api 연결
- [x] 대표 이미지 선택
- [x] 대표 이미지 없을 때 post 안되는 오류 수정
- [x] 사진 업로드 (촬영/갤러리)
- [x] 이전 작품 불러오기

## 💬 ETC
- 기타 사항
