### ISSUE TITLE
fix Record modify

### ISSUE THREAD

**Issue by lse415** [Artview2024/Artview_FE#59]
## 📝Description
> 기록 수정 이슈 해결

## ☑️Todo
- [x] 기존의 내용 - 모두 String
- [x] 새롭게 추가된 아트리스트/대표사진 이미지 - multifile
- [x] myReviewsId 연결
- [x] 추가된 아트리스트 addImage
- [x] 대표사진 설정

## 💬 ETC
- 기타 사항
