### ISSUE TITLE
프로필 수정 UI

### ISSUE THREAD

**Issue by lse415** [Artview2024/Artview_FE#78]
## 📝Description
> 프로필 수정 UI

## ☑️Todo
- [x] 이름, 닉네임 가져오기
- [x] 정보 input UI
- [x] 성별, 생년월일 선택
- [ ] 닉네임 중복체크

## 💬 ETC
- 기타 사항
