### ISSUE TITLE
기록 사진 필수 

### ISSUE THREAD

**Issue by lse415** [Artview2024/Artview_FE#97]
## 📝Description
> 기록하기 과정에서 사진 업로드 필수. 

## ☑️Todo
- [ ] 사진 필수 모달 컴포넌트 제작
- [ ] 사진 없이 이전, 다음 버튼 클릭 시 사진 업로드 필수라는 경고 모달 show
- [ ] 사진 없는 artList 있을 시 기록 종료 버튼 눌렀을 때 사진 업로드 필수라는 경고 모달, 등록 안됨 show

## 💬 ETC
- 기타 사항
